### ISSUE TITLE
something jre crash with async mod?

### ISSUE THREAD

**Issue by KITE2459** [AxalotLDev/Async#22]
[crash-2024-11-03_23.17.47-server.txt](https://github.com/user-attachments/files/17610749/crash-2024-11-03_23.17.47-server.txt)

[env]
graalvm-22-arm
mcversion 1.21.3
async-0.1.2-alpha.1-1.21.3

**Comment by FurryMileon** [comment]
[async-0.1.2+alpha.2-1.21.3.zip](https://github.com/user-attachments/files/17610817/async-0.1.2%2Balpha.2-1.21.3.zip)
try this version

**Comment by KITE2459** [comment]
still crashed with same error
not the crash report, what other information can I give you that would help troubleshoot the error?

**Comment by KITE2459** [comment]
The server booted normally and I was able to connect,
but after connecting, while chunk loading in 5 minutes,
the server suddenly stopped and the connection was disconnected due to a timeout, and a crash report was generated.

**Comment by suerion** [comment]
Please send also Latest.log

**Comment by KITE2459** [comment]
[2024-11-03-6.log](https://github.com/user-attachments/files/17611013/2024-11-03-6.log)

**Comment by suerion** [comment]
you should try to log also with log4j2, https://www.reddit.com/r/admincraft/comments/69271l/guide_controlling_console_and_log_output_with/

**Comment by FurryMileon** [comment]
> [2024-11-03-6.log](https://github.com/user-attachments/files/17611013/2024-11-03-6.log)

Could you share the modpack? If not, we could try removing mods one by one to isolate the issue. Based on what you're saying, there's a good chance that C2me mod is causing the problem.

**Comment by KITE2459** [comment]
test finished
c2me and async crashed

**Comment by wicivo** [comment]
> test finished c2me and async crashed

How to reproduce this, I've been testing c2me+ async for about 4 days and not getting this

**Comment by wicivo** [comment]
Also I would not recommend you to use mods from someaddon, I don't think they can really improve server performance and besides they have closed source code

**Comment by wicivo** [comment]
> > test finished c2me and async crashed
> 
> How to reproduce this, I've been testing c2me+ async for about 4 days and not getting this

Previously this could be reproduced by teleporting all entities to yourself, while loading chunks, and there is also enter the end gateway, but this has been fixed

**Comment by wicivo** [comment]
Also what does entityculling do in your server if it is a client mod, it does nothing on the server side

**Comment by suerion** [comment]
> Also I would not recommend you to use mods from someaddon, I don't think they can really improve server performance and besides they have closed source code

Hey, i know it is closed source, but someaddons mods are improving the server, but this is not the issue here. And someaddons mods can be decompiled, then you could see the code also ;)

It would be better, you would give the modpack to use an dev enviroment, to look on the errors.

On 1.21.1 Fabric the watchdog issue is still given, hope the fix would be release soon. On 1.21.3

You need to test more on the pack. @KITE2459

**Comment by suerion** [comment]
I had also seen, some configs are corrupted, did you also use an clean server?

**Comment by KITE2459** [comment]
[crash-2024-11-06_11.50.36-server.txt](https://github.com/user-attachments/files/17650441/crash-2024-11-06_11.50.36-server.txt)
[latest.log](https://github.com/user-attachments/files/17650443/latest.log)

After completely removing the config, I rebooted and only added async and c2me as the mods.

The crash still occurs only at certain coordinates during chunk loading,
but it did not crash when only one of the mods, async or c2me, existed.

**Comment by KITE2459** [comment]
fixed on async 0.1.4 alpha3
compat with c2me 0.3.0+rc.1.0 preview for 1.21.3
thank you very much :)
